'use strict';
const URL_API='https://wyhkvlrhevqswpqqgtsi.supabase.co/functions/v1/shai-api';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Lima',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const pct=x=>x==null?'Sin datos':(x*100).toFixed(1)+'%',num=x=>x==null?'—':Number(x).toFixed(2),sol=x=>'S/ '+(x/100).toFixed(2);
let token=sessionStorage.getItem('shai-session')||'',matches=[],selected=null,legs=[],review=null,entries=[],requestID=null;
async function api(action,data={}){const r=await fetch(URL_API,{method:'POST',headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},body:JSON.stringify({action,...data}),signal:AbortSignal.timeout(25000)});const v=await r.json();if(!r.ok){if(r.status===401&&action!=='login'){sessionStorage.removeItem('shai-session');token='';$('app').hidden=true;$('login').hidden=false;}throw Error(v.error||'No se pudo completar.');}return v;}
function message(s){$('message').textContent=s;}
async function run(button,fn){button.disabled=true;message('');try{await fn();}catch(e){message(e.message);}finally{button.disabled=false;}}
function invalidate(){review=null;requestID=null;$('review').innerHTML='';$('save-bet').hidden=true;}
function legLabel(l){const scope={total:'total',home:'local',away:'visitante'},period={total:'partido completo',primero:'primer tiempo',segundo:'segundo tiempo'};return l.metric==='resultado'?{home:'Gana local',draw:'Empate',away:'Gana visitante'}[l.pick]:`${l.metric} · ${scope[l.scope]} · ${period[l.period]} · ${l.pick==='over'?'más':'menos'} ${l.line}`;}
async function account(){if(!token)return;const a=await api('account');$('login').hidden=true;$('logout').hidden=false;$('pending').hidden=a.allowed;$('pending').textContent='Cuenta: '+a.name+' · estado: '+a.access.state+'. El administrador puede aprobar o renovar tu acceso desde su computadora.';$('app').hidden=!a.allowed;if(a.allowed){$('account').textContent='Cuenta: '+a.name+' · acceso hasta '+(a.access.expires_on||'sin vencimiento')+' · partidos hasta '+(a.access.matches_until||'sin límite');if(a.access.matches_until){$('from').max=a.access.matches_until;$('to').max=a.access.matches_until;}await load();}}
async function load(){const v=await api('matches',{from:$('from').value,to:$('to').value});matches=v.matches;const old=$('league').value;$('league').innerHTML='<option value="">Todas las competiciones</option>'+[...new Set(matches.map(m=>m.league))].sort().map(l=>`<option>${esc(l)}</option>`).join('');$('league').value=old;renderMatches();}
function renderMatches(){const league=$('league').value;const filtered=matches.filter(m=>!league||m.league===league);$('matches').innerHTML=filtered.map(m=>`<button class="match" data-match="${esc(m.match_key)}"><small>${esc(m.match_day+' · '+m.league+' · '+m.season)}</small><span><strong>${esc(m.home)}</strong> — <strong>${esc(m.away)}</strong></span><small>${m.payload.fixture.goles_local==null?'Sin resultado publicado':esc(m.payload.fixture.goles_local+' – '+m.payload.fixture.goles_visitante)} · sincronizado ${esc(m.synced_at.slice(0,16))}</small></button>`).join('')||'<p>No hay partidos publicados para este filtro. Puede faltar la sincronización de la laptop.</p>';}
function detail(m){selected=m;const b=m.payload.estimate;$('detail').innerHTML=`<small>${esc(m.league+' · '+m.match_day)}</small><h2>${esc(m.home+' – '+m.away)}</h2><p>${b?'Análisis calculado: '+esc(b.generated_at||m.calculated_at):'No hay estimación guardada para este partido.'}</p><p>${esc(b?.notice||'')}</p><div class="metrics"><label>Estadística<select id="metric"><option value="goles">Goles</option><option value="corners">Córners</option><option value="amarillas">Amarillas</option><option value="rojas">Rojas</option></select></label><label>Período<select id="period-metric"><option value="total">Partido completo</option><option value="primero">Primer tiempo</option><option value="segundo">Segundo tiempo</option></select></label><label>Alcance<select id="scope"><option value="total">Total</option><option value="home">Local</option><option value="away">Visitante</option></select></label></div><div id="statistics"></div><h3>Añadir una selección</h3><label>Mercado<select id="pick-metric"><option value="resultado">Resultado 1X2</option><option value="goles">Goles</option><option value="corners">Córners</option><option value="amarillas">Amarillas</option><option value="rojas">Rojas</option></select></label><label id="result-label">Resultado<select id="pick-result"><option value="home">Gana local</option><option value="draw">Empate</option><option value="away">Gana visitante</option></select></label><div id="counts" hidden><p>Usa el período y el alcance elegidos arriba.</p><label>Más o menos<select id="pick-side"><option value="over">Más de</option><option value="under">Menos de</option></select></label><label>Línea<select id="pick-line">${Array.from({length:31},(_,i)=>`<option>${i+.5}</option>`).join('')}</select></label></div><button id="add-leg">Añadir a mi selección</button>`;
 for(const id of ['metric','period-metric','scope'])$(id).onchange=statistics;$('pick-metric').onchange=()=>{const counts=$('pick-metric').value!=='resultado';$('counts').hidden=!counts;$('result-label').hidden=counts;$('pick-line').value=$('pick-metric').value==='corners'?'5.5':'1.5';};$('add-leg').onclick=()=>{if(legs.length>=8){message('Máximo ocho selecciones.');return;}const metric=$('pick-metric').value;legs.push({key:m.match_key,match:m.home+' – '+m.away,metric,period:metric==='resultado'?'total':$('period-metric').value,scope:metric==='resultado'?'total':$('scope').value,pick:metric==='resultado'?$('pick-result').value:$('pick-side').value,line:Number($('pick-line').value)});renderLegs();};statistics();}
function statistics(){const b=selected.payload.estimate,m=b?.metrics?.[$('metric').value+'_'+$('period-metric').value],s=m?.[$('scope').value],out=b?.metrics?.goles_total?.outcomes;const outcomes=out?`<p>Local ${pct(out[0])} · Empate ${pct(out[1])} · Visitante ${pct(out[2])}</p>`:'';$('statistics').innerHTML=outcomes+(!m?.available||!s?'<p>No hay datos suficientes para esta estadística y período.</p>':`<p>Media: <strong>${num(s.mean)}</strong> · Intervalo 80%: ${esc((s.interval80||[]).join('–'))} · Al menos uno: ${pct(s.at_least_one)}</p><table><tr><th>Línea</th><th>Más de</th><th>Menos de</th></tr>${(s.thresholds||[]).map(t=>`<tr><td>${t.line}</td><td>${pct(t.over)}</td><td>${pct(t.under)}</td></tr>`).join('')}</table>`);}
function renderLegs(){invalidate();$('legs').innerHTML=legs.map((l,i)=>`<div><button data-remove="${i}" aria-label="Quitar selección ${i+1}">×</button><strong>${esc(l.match)}</strong><br>${esc(legLabel(l))}</div>`).join('')||'<p>Todavía no hay selecciones.</p>';}
async function ledger(){entries=(await api('records')).entries;const balance=entries.reduce((s,r)=>s+(r.kind==='deposito'?r.amount_cents:r.kind==='retiro'?-r.amount_cents:-r.amount_cents+(r.returned_cents||0)),0);$('balance').textContent='Bank disponible: '+sol(balance)+' · Pendiente: '+sol(entries.filter(r=>r.kind==='apuesta'&&r.returned_cents==null).reduce((s,r)=>s+r.amount_cents,0));$('entries').innerHTML='<div class="scroll"><table><tr><th>Fecha / descripción</th><th>Importe</th><th>Devuelto</th><th>Estado</th></tr>'+entries.map(r=>`<tr><td>${esc(r.day+' · '+r.kind)}<br>${esc(r.payload.description)}</td><td>${sol(r.amount_cents)}</td><td>${r.returned_cents==null?'—':sol(r.returned_cents)}</td><td>${esc(r.payload.state||'registrado')}</td></tr>`).join('')+'</table></div>';summary();}
function summary(){const size={day:10,month:7,year:4}[$('period').value],groups={};for(const r of entries){const day=(r.settled_on||r.day).slice(0,size);const g=groups[day]??={won:0,lost:0,profit:0};if(r.kind==='apuesta'&&r.returned_cents!=null){g.profit+=r.returned_cents-r.amount_cents;if(r.returned_cents>r.amount_cents)g.won++;if(r.returned_cents<r.amount_cents)g.lost++;}}$('summary').innerHTML='<table><tr><th>Período</th><th>Ganadas / perdidas</th><th>Resultado neto cerrado</th></tr>'+Object.entries(groups).sort((a,b)=>b[0].localeCompare(a[0])).map(([d,g])=>`<tr><td>${esc(d)}</td><td>${g.won} / ${g.lost}</td><td>${sol(g.profit)}</td></tr>`).join('')+'</table>';}
$('from').value=$('to').value=$('day').value=today();
$('auth').onsubmit=e=>{e.preventDefault();run(e.submitter,async()=>{const action=$('auth-mode').value,v=await api(action,{name:$('name').value,password:$('password').value});$('password').value='';if(action==='signup'){message(v.message);$('auth-mode').value='login';}else{token=v.access_token;sessionStorage.setItem('shai-session',token);await account();}});};
$('logout').onclick=()=>{sessionStorage.removeItem('shai-session');location.reload();};$('load').onclick=e=>run(e.target,load);$('league').onchange=renderMatches;$('matches').onclick=e=>{const b=e.target.closest('[data-match]');if(b)detail(matches.find(m=>m.match_key===b.dataset.match));};$('legs').onclick=e=>{const b=e.target.closest('[data-remove]');if(b){legs.splice(Number(b.dataset.remove),1);renderLegs();}};$('odds').oninput=invalidate;
$('verify').onclick=e=>run(e.target,async()=>{invalidate();if(!legs.length)throw Error('Añade una selección.');const keys=new Set(legs.map(l=>l.key));const signature=JSON.stringify([legs,$('odds').value]);const v=await api('verify',{ticket:{key:legs[0].key,mode:legs.length===1?'simple':keys.size>1?'multiple':'combinada',odds:$('odds').value,legs}});if(signature!==JSON.stringify([legs,$('odds').value]))throw Error('Cambió la selección. Verifica nuevamente.');review=v;requestID=crypto.randomUUID();const r=v.report;$('review').innerHTML=`<h3>${esc(r.verdict)}</h3><p>Cuota exige: ${pct(r.implied)}. Límites de coincidencia: ${pct(r.probability_low)} – ${pct(r.probability_high)}.</p><table><tr><th>Partido / selección</th><th>Probabilidad</th><th>Cuota de equilibrio individual</th></tr>${r.rows.map(x=>`<tr><td>${esc(x.match)}<br>${esc(legLabel(x))}</td><td>${pct(x.probability)}</td><td>${num(x.fair_odds)}</td></tr>`).join('')}</table><p>${esc(r.explanation)}</p>`;$('confirmed').checked=false;$('save-bet').hidden=false;});
$('save-bet').onsubmit=e=>{e.preventDefault();run(e.submitter,async()=>{if(!review||!$('confirmed').checked)throw Error('Verifica y confirma la selección.');await api('move',{movement:{kind:'apuesta',day:today(),amount_cents:Math.round(Number($('stake').value)*100),request_id:requestID,review_id:review.review_id,decision:'confirmada'}});legs=[];renderLegs();$('ledger').hidden=false;await ledger();message('Registro guardado. No se envió ninguna apuesta.');});};
let moveID=crypto.randomUUID();$('movement').oninput=()=>moveID=crypto.randomUUID();$('movement').onsubmit=e=>{e.preventDefault();run(e.submitter,async()=>{await api('move',{movement:{kind:$('kind').value,day:$('day').value,amount_cents:Math.round(Number($('amount').value)*100),request_id:moveID}});moveID=crypto.randomUUID();$('amount').value='';await ledger();message('Movimiento guardado.');});};$('open-ledger').onclick=e=>run(e.target,async()=>{$('ledger').hidden=false;await ledger();$('ledger').scrollIntoView({behavior:'smooth'});});$('period').onchange=summary;
account().catch(e=>message(e.message));setInterval(async()=>{if(!token)return;try{const a=await api('account');if(!a.allowed){$('app').hidden=true;$('pending').hidden=false;$('pending').textContent='El acceso está pendiente, vencido o revocado.';}else if($('app').hidden)await account();}catch(e){message(e.message);}},30000);

